version: "3.8"

services:
  app:
    build: .
    ports:
      - "3310:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
    # add your own media paths here
      - "/media/Storage3/Movies/Anime Movies:/media/movies/anime"
      - "/media/Storage3/Movies/Bollywood:/media/movies/bollywood"
      - "/media/Storage3/Movies/Hollywood:/media/movies/hollywood"
      - "/media/Storage3/Movies/Korean Movies:/media/movies/korean"
      - "/media/Storage3/Movies/South Action:/media/movies/south"
      - "/media/Storage3/Web Series/Anime Series:/media/series/anime"
      - "/media/Storage3/Web Series/K Drama:/media/series/k-drama"
      - "/media/Storage3/Web Series/Web Series - English:/media/series/english"
      - "/media/Storage3/Web Series/Web Series - Hindi:/media/series/hindi"
    restart: unless-stopped
