name: Deploy to Home Server

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'  # Adjust based on your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to Home Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOME_SERVER_HOST }}
          username: ${{ secrets.HOME_SERVER_USERNAME }}
          key: ${{ secrets.HOME_SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.HOME_SERVER_USERNAME }}/samflix-backend
            git pull
            docker-compose down
            docker system prune -a
            docker-compose up -d --build
